export { default as TopBar } from './TopBar.astro';
export { default as Navbar } from './Navbar.astro';
// export { default as Footer } from './Footer.astro';
export { default as QuienesSomos } from './QuienesSomos.astro';
export { default as FlooringSection } from './FlooringSection.astro';
export { default as ImageComparison } from './imageComparison/ImageComparison.astro';
// export { default as OpinionesCarousel } from './opinionesCarousel/OpinionesCarousel.astro';
export { default as ContactForm } from './ContactForm.astro';
export { default as ShadersSliderMultilingual } from './ShadersSlider/ShadersSliderMultilingual.astro';
export { default as ReviewsCarousel } from './ReviewsCarousel.astro';
export { default as ProjectSection } from './ProjectSection.astro';